### PR TITLE
Fix gradlew and update to the latest version

### PR DESCRIPTION
**Pull request by emartynov**
I noticed that gradle was not starting. So I tried to update it to the latest and it looks like work. I'm looking at the changes and can not say what was the cause and what is the fix.

### CODE REVIEW

**Comment by noloman** [comment]
Thanks for the PR @emartynov :)

**Comment by emartynov** [comment]
It still fails! It runs locally for me.

**Comment by emartynov** [comment]
This is the problem `!gradle-wrapper.jar`

**Comment by emartynov** [comment]
Let me make another PR

**Pull request merged**
